<?php
$labels = array();
$labels['gravatar_plugin'] = 'Catálogo Gravatar';
$labels['gravatar_use'] = 'Usar Gravatar';
$labels['gravatar_size'] = 'Tamanho do avatar (px)';
$labels['gravatar_rating'] = 'Classificação do avatar';
$labels['gravatar_G'] = 'Classificação G';
$labels['gravatar_PG'] = 'Classificação PG';
$labels['gravatar_R'] = 'Classificação R';
$labels['gravatar_X'] = 'Classificação X';
$labels['gravatar_use_custom'] = 'Usar API definida (tem sempre preferência)';
